services:
  - type: web
    name: monlam ai tools staging
    env: node
    plan: standard
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/OpenPecha/monlam_ai_tools.git
    branch: staging
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: staging-monlam-tools-pg
          property: connectionString

databases:
  - name: staging-monlam-tools-pg
    plan: standard
