services:
  - type: web
    name: monlam ai tools
    env: node
    plan: free
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/OpenPecha/monlam_ai_tools.git
    branch: main
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: ~16.14.2
      - key: NODE_ENV
        value: production
