export const lamas = [
  {
    id: 1,
    name: "H.H. GYANA VAJRA RINPOCHE",
    image: "/assets/lamas/1.jpg",
    description: "Lama 1 description",
  },
  {
    id: 2,
    name: "H.H. GANDEN TRI RINPOCHE",
    image: "/assets/lamas/2.png",
    description: "Lama 1 description",
  },
  {
    id: 3,
    name: "H.H. KARMAPA OGYEN TRINLEY DORJE",
    image: "/assets/lamas/3.png",
    description: "Lama 1 description",
  },
  {
    id: 4,
    name: "H.H. MENRI TRIZIN",
    image: "/assets/lamas/4.jpg",
    description: "Lama 1 description",
  },
  {
    id: 5,
    name: "H.E. JONANG GYALTSAB RINPOCHE",
    image: "/assets/lamas/5.png",
    description: "Lama 1 description",
  },
  {
    id: 6,
    name: "H.E. SHECHEN RABJAM RINPOCHE ",
    image: "/assets/lamas/6.jpg",
    description: "Lama 1 description",
  },
  {
    id: 7,
    name: "H.E. CHAMGON KENTING TAI SITU RINPOCHE",
    image: "/assets/lamas/7.jpg",
    description: "Lama 1 description",
  },
  {
    id: 8,
    name: "H.E. DZONGSAR JAMYANG KHYENTSE RINPOCHE",
    image: "/assets/lamas/8.png",
    description: "Lama 1 description",
  },
  {
    id: 9,
    name: "H.E. YONGZIN LING CHOGTRUL RINPOCHE",
    image: "/assets/lamas/9.jpg",
    description: "Lama 1 description",
  },
  {
    id: 10,
    name: "H.E. PROF SAMDHONG RINPOCHE",
    image: "/assets/lamas/10.png",
    description: "Lama 1 description",
  },
  {
    id: 11,
    name: "H.E. KIRTI RINPOCHE",
    image: "/assets/lamas/11.png",
    description: "Lama 1 description",
  },
  {
    id: 12,
    name: "H.E. CHOGTRUL MUGSANG KUCHEN RINPOCHE",
    image: "/assets/lamas/12.png",
    description: "Lama 1 description",
  },
  {
    id: 13,
    name: "H.E. TARTHANG RINPOCHE",
    image: "/assets/lamas/13.png",
    description: "Lama 1 description",
  },
];
