export const lamas = [
  {
    id: 1,
    name: "H.H. GYANA VAJRA RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 2,
    name: "H.H. GANDEN TRI RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 3,
    name: "H.H. KARMAPA OGYEN TRINLEY DORJE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 4,
    name: "H.H. MENRI TRIZIN",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 5,
    name: "H.E. JONANG GYALTSAB RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 6,
    name: "H.E. SHECHEN RABJAM RINPOCHE ",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 7,
    name: "H.E. CHAMGON KENTING TAI SITU RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 8,
    name: "H.E. DZONGSAR JAMYANG KHYENTSE RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 9,
    name: "H.E. YONGZIN LING CHOGTRUL RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 10,
    name: "H.E. PROF SAMDHONG RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 11,
    name: "H.E. KIRTI RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 12,
    name: "H.E. CHOGTRUL MUGSANG KUCHEN RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
  {
    id: 13,
    name: "H.E. TARTHANG RINPOCHE",
    image: "",
    description: "Lama 1 description",
  },
];
